"""Add indexes to StageResult and Stage tables

Revision ID: 7ba311775a9a
Revises: a00e6c4613f1
Create Date: 2025-11-15 21:31:38.489293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba311775a9a'
down_revision = 'a00e6c4613f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_results', schema=None) as batch_op:
        batch_op.create_index('idx_rider_stage', ['rider_id', 'stage_id'], unique=False)
        batch_op.create_index('idx_stage_rank', ['stage_id', 'rank'], unique=False)
        batch_op.create_index('idx_team_rank', ['team_id', 'rank'], unique=False)

    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stages_edition_id'), ['edition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stages_edition_id'))

    with op.batch_alter_table('stage_results', schema=None) as batch_op:
        batch_op.drop_index('idx_team_rank')
        batch_op.drop_index('idx_stage_rank')
        batch_op.drop_index('idx_rider_stage')

    # ### end Alembic commands ###
